### ISSUE TITLE
many versions in package.json not locked.

### ISSUE THREAD

**Issue by BenEllerby** [Theodo-UK/react-boilerplate#14]
e.g.     "chalk": "^1.1.3"

Should lock:     "chalk": "1.1.3"

**Comment by n6g7** [comment]
That's why we have a [lockfile](https://github.com/Theodo-UK/react-boilerplate/blob/master/yarn.lock). 😉

**Comment by williamdclt** [comment]
Yeah I agree that it's what the lockfile is for. I'll close, it can be reopened if there's a compelling argument in favor!
